### ISSUE TITLE
Background Image

### ISSUE THREAD

**Issue by ZXant** [laedit/new-tab-moment#108]
Trying to place a background image through Custom CSS as the following, but it doesn't seems to work. Please, verify if would be the proper way.

```
body {
 background-image: url("http://blog.dubspot.com/files/2012/06/DJM_800_and_Technics_Turntable_by_pulsarmedia.jpg");
 background-color: #cccccc;
}
```

Thanks, ZXant

**Comment by laedit** [comment]
Thanks for using my extension!
For the background you have to use `!important` to override style already in place:
``` css
body {
 background-image: url("http://blog.dubspot.com/files/2012/06/DJM_800_and_Technics_Turntable_by_pulsarmedia.jpg") !important;
 background-color: #cccccc !important;
}
```
But it seems that the image can't be used from outside the dubspot website, because it doesn't appears but if I change for a public image like [this one](https://interactive-examples.mdn.mozilla.net/media/examples/lizard.png), it works.
